### ISSUE TITLE
Contenidos de carrusel en versión móvil (altura)

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#1]
El logotipo no se muestra centrado en la versión de celular 

![image](https://user-images.githubusercontent.com/9852450/28396399-cb40dea4-6cc0-11e7-9233-ab268691a77b.png)

**Comment by JuanCZD** [comment]
Adecuando Logo en versión movil:
En  index.html
	Line 51-->  cambio class @ id="Ahorratec-centro"
	Line 54-->  borro class="text-center navbar-brand"

Enn  Hoja_de_Estilo.css
	Line 724-->  **@media** se agrega en;
	Line 729-->  #Ahorratec-Centro {float: left;}

**Comment by JuanCZD** [comment]
Solucionado logo centrado en versión movil  y al desaparecer el menú.
@vazeri 

**index.html:**
_código modificador.-_ 

`<div class="text-center">
 <a href="#inicio" class="text-center navbar-brand"><img src="images/templatemo_logo.png" alt="Logo Ahorratec" title="Ahorratec.org" /></a></div>`

_por.-_

`<div id="Ahorratec-Centro">
                                <a href="#inicio"><img src="images/templatemo_logo.png" class="img-responsive" alt="Logo Ahorratec" title="Ahorratec.org" /></a>
                            </div>`

**Hoja_de_Estilo.css**
Se añade modificación en en `@media` line 724

`@media (min-width: 768px) {
...  
  #Ahorratec-Centro {
        float: left;}
...
} 
`

**Tamaño Móvil** _lo mas reducido de mi notebook_

<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/logo_movil.png" />

**Tamaño Móvil** _smartphone_

<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/logo_smartphone.png" />
**Tamaño Sin menu**

<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/logo_sin_menu.png" />

**Comment by vazeri** [comment]
Quedo muy bien puedes ajustar tambien esta otra resolucion? (asumo que es tableta, cuando se crea una segunda fila para el menu)

![image](https://user-images.githubusercontent.com/9852450/28625243-3b1909b6-71e1-11e7-957d-9f7fb1c469ad.png)

**Comment by vazeri** [comment]
Aqui un pequeño detalle me parece que mezclamos los problemas https://github.com/Ahorratec/ProtoWeb/issues/1 con https://github.com/Ahorratec/ProtoWeb/issues/7

He modificado los titulos y contenidos para dejarlo mas claro en realidad se resolvio https://github.com/Ahorratec/ProtoWeb/issues/7 (a reserva de revisar el caso que mencione) con lo que se ha comentado hasta el momento

**Comment by JuanCZD** [comment]
@vazeri podrías revisar.

Posible solución a Ahorratec#1
Se ajustan casa y negocio.
Se logro subir las imágenes para que salgan mejor en versión móvil.

https://github.com/JuanCZD/ProtoWeb/tree/Posible-Soluci%C3%B3n-Carrusel

**Fallo**
No se logra reducir el alto del carrusel, creo de pende de las imágenes y la configuración en la hoja de estilos.

**Sugerencia**
Realizar desde cero el carrusel para realizar ajuste a imágenes y posiblemente añadir el texto directamente en las imágenes para evitar herreros de encuadre.

_Nota: No quiero juntar con mi master hasta que me des tu opinión_

**Comment by vazeri** [comment]
reviso

**Comment by vazeri** [comment]
d237573

**Comment by vazeri** [comment]
te respondi en https://github.com/JuanCZD/ProtoWeb/commit/d237573292b8bd05a67977146bb48e1ce726b3d5 , dado a que parece que duplicaste el comentario

**Comment by vazeri** [comment]
Lo dejamos pendiente
