### ISSUE TITLE
Hogar y Negocio se colapsan uno sobre otro en modo celular (mobile)

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#10]
Una solución posible sería agregar un nuevo módulo del carrusel para evitar que aparezcan al mismo tiempo y cada uno salga a su tiempo (centrados preferentemente)

![image](https://user-images.githubusercontent.com/9852450/28489311-e38c24d8-6e86-11e7-9185-3414faf0f093.png)

**Comment by vazeri** [comment]
Solucionado (en tu servidor)

**Comment by vazeri** [comment]
en cuanto lo subas cierro el problema

**Comment by JuanCZD** [comment]
Ya solicite el  Pull requests lo revisa 
#22

**Comment by vazeri** [comment]
Otra propuesta solucion, pruebala para ver que no tenga errores o fallos graficos en centrar en cualquier resolucion 

 https://github.com/Ahorratec/ProtoWeb/tree/Carrusel-patch1

**Comment by JuanCZD** [comment]
desde escritorio presionado F12 queda bien pero lo subo a mi servidor y en mi cel si queda centrado, pero se muestra un degradado creo del carrusel te mando capturas.

**Comment by vazeri** [comment]
Solucionado parcialmente aun con bugs en ciertos teléfonos de gama baja, se reemplazará. Carrusel a futuro
