### ISSUE TITLE
Sección "Asi Funciona" no cuadra

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#2]
El número 3 está vacío y en su lugar un espacio vacío, mientras el número 3 toma el lugar del 4 y el número 4 se recorre a otro renglón, esto solo pasa en ciertas resoluciones reducidas

![image](https://user-images.githubusercontent.com/9852450/28396489-52440e08-6cc1-11e7-9927-57bacb3e8c79.png)

**Comment by JuanCZD** [comment]
Ok no te avía entendido ya lo cheque  lo del espacio en blanco

**Comment by vazeri** [comment]
Solo sucede en ciertas resoluciones, intermedias entre el modo teléfono y modo escritorio, hay que revisar porque

**Comment by vazeri** [comment]
Arreglado con #16
