### ISSUE TITLE
Centrar TITULOS y SUBTITULOS  de APLICACIONES (Solo en version movil)

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#25]
Uno de los ultimos detalles centrar los titulos y subtitulos de la seccion APLICACIONES (solo en version movil)

![image](https://user-images.githubusercontent.com/9852450/28926357-29d56e9a-782d-11e7-891d-0efab83b92d1.png)

**Comment by JuanCZD** [comment]
@vazeri 
Solucionado revisa en
https://juanczd.github.io/ProtoWeb/

**Comment by vazeri** [comment]
Arreglado
