### ISSUE TITLE
Fondos se reducen al cambiar el tamaño de la página 

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#3]
Al reducir el tamaño de la pagina ( Ctrl - ) los fondos de pantalla de algunas secciones se reducen y descuadran (deben quedar estáticos justo como en el fondo de circuito blanco de la segunda imagen )

![image](https://user-images.githubusercontent.com/9852450/28396528-9c596506-6cc1-11e7-825e-cc647960a472.png)

Idealmente así deben quedar: (no cambiar de tamaño ni posición independientemente del nivel del zoom)

![image](https://user-images.githubusercontent.com/9852450/28396570-e0f2de4a-6cc1-11e7-9a0b-7ccc17242fa6.png)

**Comment by JuanCZD** [comment]
Ok te refieres al fondo verde.

**Comment by vazeri** [comment]
el fondo verde y el de hasta abajo que tiene un escritorio

**Comment by JuanCZD** [comment]
ok enterado

**Comment by ghost** [comment]
I've already solved your problem, do you still need help?

**Comment by vazeri** [comment]
i just merged the changes it's a nice attempt however, it seems to work only up to a certain zoom if i go to the max it still breaks, however it's currently better than before tho, ideally it should be static as the carrousel white background (the one at the top with gray circuits), thanks for your time tho 

![image](https://user-images.githubusercontent.com/9852450/28488707-d195e3ce-6e75-11e7-8ee3-067174944761.png)


![image](https://user-images.githubusercontent.com/9852450/28488694-b90795e6-6e75-11e7-8865-84a8a7e2a7cd.png)

**Comment by vazeri** [comment]
solucionado por @JuanCZD

**Comment by JuanCZD** [comment]
Revisando la pagina en iphone el ultimo fondo no se muestra e buscado en interne pero no encuentro la causa ya que se muestra de la misma manera que los fondos verdes y el formato de imagen es JPG así que no puede ser, a ver si podrías ayudarme por favor.

Web en Iphone:

**Safari**

<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/iphone_safari.jpeg" />


**Chrome**

<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/iphone_chrome.jpeg" />

**Comment by vazeri** [comment]
Estoy checando lo que dices en tu master pero no puedo replicar el problema

![image](https://user-images.githubusercontent.com/9852450/28682632-3dfbc9d8-72c3-11e7-971d-57cd540dc8e5.png)

**Comment by ghost** [comment]
Hola!
Disculpa el atraso al responder los correos, voy a checar la página y te ayudo.

**Comment by vazeri** [comment]
Saludos, gracias alejandro

**Comment by JuanCZD** [comment]
Hola @alejandro6901  gracias por la colaboración.
@vazeri ya lo revise el error esta al parecer esta en "Hoja_de_Estilo.css" en la clase ".templatemo-footer" linea 521.

`.templatemo-footer {
    background-image: url('../images/donativos.jpg');
	background-repeat: no-repeat;
	background-position: center bottom;
	background-attachment: fixed;
	background-size: auto 100%;
}`

Es cuestión de eliminar el 100%, que agregue para resolver los de los fondos verdes, lo podrías corroborar, en pc y con Zoom:25% se se ve bien.
Lo de más fondos quedan bien.

**Comment by vazeri** [comment]
No encuentro un branch en tu perfil con dicho cambio, los tienes disponible en linea?

**Comment by vazeri** [comment]
Depues de todos los commits termine Realizando unos cambios en el Master para dejarlo como estaba inicialmente sin embargo el problema aun existe parcialmente dejo abierto el problema 

Aun se puede ver en https://ahorratec.github.io/ProtoWeb/

![image](https://user-images.githubusercontent.com/9852450/28926990-00c82022-782f-11e7-9ead-45c92c633084.png)

**Comment by TopherHamn** [comment]
hola, estoy disponible y me gustaria colaborar, podria explicarme detalladamente cual es el problema?

**Comment by vazeri** [comment]
@TopherHamn buen dia, gracias por su apoyo, básicamente intentamos hacer que el ultimo fondo (el de hasta abajo) mantenga sus dimensiones en alto y ancho, siempre centrado,  en cualquier resolución y zoom, (similar al fondo blanco superior del carrusel de imagenes) sin embargo parece que tenemos un problema de alguna funcion sobreescribiendo la configuracion de la clase en algun lugar que no hemos identificado, la clase que maneja este fondo del footer es llamada, template_footer pero algunas modificaciones conocidas para lograr este efecto, no surten efecto por lo que el mejor arreglo actual es el presente

**Comment by vazeri** [comment]
Solucionado por @TopherHamn en https://github.com/Ahorratec/ProtoWeb/pull/41
