### ISSUE TITLE
Ocultar menu en resolucion para tabletas

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#31]
Esto se muestra en ciertas tabletas y resoluciones, idealmente el logo (como en las versiones de celular) debe quedar centrado y el menú desaparecer, 
 
![image](https://user-images.githubusercontent.com/9852450/28944430-216ee142-7868-11e7-9881-8b56a263b923.png)

**Comment by JuanCZD** [comment]
Solución excelente a la resolución del iPad  pero en resolución alrededor de 600 se sube el carrusel favor de revisar en https://juanczd.github.io/ProtoWeb/
@vazeri 

> El menú se oculta al ocupara un renglón mas, esto es en una resolución de 992.

**Comment by vazeri** [comment]
perfecto, buen trabajo
