### ISSUE TITLE
Agregar fuente Tw Cen MT a Encabezados, titulos, subtitulos y menus

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#36]
Para mantener un solo estilo todos los mencionados en el titulo deben usar la fuente Tw Cen MT (fuente utilizada en el logotipo de Ahorratec en la parte "Monitoreo de EnergÍa"), las imagenes que lleguen a utilizar títulos o subtítulos ya han sido modificadas por mi,

**Comment by JuanCZD** [comment]
Revisa si en dispositivos móviles u otros si se agrega la fuente correctamente porque al parecer solo esta pre-instalada en Windows

https://juanczd.github.io/ProtoWeb/

**Comment by vazeri** [comment]
Si se ve en android 7.0 y tambien en windows, ya probaste en iphone ?

**Comment by JuanCZD** [comment]
si ya revise en iphone se ve bien 👍
