### ISSUE TITLE
Implementación total de Fontello

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#38]
Seria bueno que reemplazar todos los gifs/pngs de la barra superior e inferior azul (algunos ocultos en el circulo rojo) por fontello

![image](https://user-images.githubusercontent.com/9852450/28999234-a2594c8c-7a04-11e7-9fea-69392c3fc0a8.png)

![image](https://user-images.githubusercontent.com/9852450/28999235-aefefd9c-7a04-11e7-90d4-4d08e8483328.png)

phone.png
location.png
globe.png
email.png

y agregar un par para los botones ocultos (comentados en index) de

contacto
tienda
licencias
aviso de privacidad

Todos estos últimos en color amarillo #D9A300 y con un tamaño aprox de 19px, (o que no supere la altura del contenedor azul)

**Comment by JuanCZD** [comment]
@vazeri  ok me acaban de llegar los correos de esta notificación, pero ya agregue los del encabezado busco los del final.
favor de revisar

**Comment by vazeri** [comment]
Solucionado en https://github.com/Ahorratec/ProtoWeb/commit/6a98a89fd8d9f7132d2c9cca5b6f6d444885dfb5

Agregue mas iconos para links futuros 
![image](https://user-images.githubusercontent.com/9852450/29049803-ca2cf386-7b9d-11e7-9104-6f54e9025bec.png)
