### ISSUE TITLE
Centrado de template_logo perdido

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#40]
En algún momento que ya busque y no pude identificar perdimos el centrado del logotipo en resoluciones pequeñas

¿puedes revisar las modificaciones que hiciste ese dia para revisar que aun estén?

Si recuerdo bien hiciste una función para centrar en hoja de estilos pero no la encuentro, y si no esta es posible que falte algo mas, de lo que pusiste, podemos recuperarlo por medio de la grafica de network pero solo tu sabes exactamente que fue lo que se perdio y en donde

![image](https://user-images.githubusercontent.com/9852450/29000141-9fbf34cc-7a28-11e7-9c1d-8902ac205cee.png)

**Comment by vazeri** [comment]
posible pista 

https://github.com/Ahorratec/ProtoWeb/commit/90dda6d879eae847e1db333395f181f65be5f727

**Comment by JuanCZD** [comment]
Ok lo revisre

**Comment by JuanCZD** [comment]
La solución esta en borrar algo de la linea 43 del index
**Actual:**

`<a href="#inicio"><img width="268" src="img/templatemo_logo.svg" maxclass="img-responsive" alt="Logo Ahorratec" title="Ahorratec.org" /></a>`

**Modificación**

`<a href="#inicio"><img width="268" src="img/templatemo_logo.svg" class="img-responsive" alt="Logo Ahorratec" title="Ahorratec.org" /></a>`

Solo es borrar el **_max_** de **_maxclass_**


Y tengo unos dudas al sincronizar github, si me puedes apoyar te lo agradezco.

**Comment by vazeri** [comment]
al quitar ese max  pasa esto 

![image](https://user-images.githubusercontent.com/9852450/29050447-9d43c198-7ba1-11e7-866a-45a403a74d0f.png)

conectate al hangouts para resolver dudas

**Comment by vazeri** [comment]
Solucion por medio de https://github.com/Ahorratec/ProtoWeb/pull/42
