### ISSUE TITLE
Error 404 Imagen (que no existe)

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#44]
Llevo rato intentando encontrar la fuente de este error sin éxito, lo dejo aquí para ver si me puedes apoyar, 

Al presionar F12 , sección consola tira un error de 404 para el archivo "web/css/img/background.jpg"

![image](https://user-images.githubusercontent.com/9852450/29158489-dad1b0f8-7d70-11e7-9860-ffe4df20c790.png)

Sobra decir que esa dirección, no existe y nunca existió, y en el código no se encuentra en ningún archivo de manera implícita, por lo que me encuentro en la búsqueda de que es lo que está causando ese error 

cambiar los nombres de background en style.css provoca que el nombre cambie en la consola sin embargo el error continua presente

**Comment by JuanCZD** [comment]
@vazeri Mira aquí ya no me sale el error.

<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/error%20404.PNG" />

el problema esta en style.css en la parte de body

<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/body.PNG"/>

Lo eliminare, solo sigo checando lo de https://github.com/Ahorratec/ProtoWeb/issues/45 y solicito el PULL
