### ISSUE TITLE
mal encuadre de descripciones de "ASI FUNCIONA"

### ISSUE THREAD

**Issue by vazeri** [Ahorratec/ProtoWeb#45]
Estaba revisando la versión móvil y encontré un problema con las divisiones (revisar padding en CSS) que se salen de la pantalla, solo ocurre en esa sección

Confirmo que se ve igual en telefonos celulares

![image](https://user-images.githubusercontent.com/9852450/29163035-d44cbaa6-7d80-11e7-8ed4-ad094ee5cec4.png)

**Comment by JuanCZD** [comment]
@vazeri mira quedaría de esta manera 
<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/as%C3%AD%20funciona%20encuadre.PNG"/> 

Solo que siento que tiene un espaciado grande entre Así funciona  y las imágenes pero no logro quitarlo 

<img src="https://raw.githubusercontent.com/JuanCZD/Cosas-aleatorias-/master/epascio%20blanco.PNG"/>

Intente con `margin` `padding` pero al cambiar de resolución se descompone todo.
Sabes como se pueda cambiar creo es por el arreglo con bootstrap
